# Generated by Django 5.2.5 on 2025-09-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': [('can_view_category', 'Can view category'), ('can_add_category', 'Can add category'), ('can_change_category', 'Can change category'), ('can_delete_category', 'Can delete category')], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'permissions': [('can_view_item', 'Can view item'), ('can_add_item', 'Can add item'), ('can_change_item', 'Can change item'), ('can_delete_item', 'Can delete item')]},
        ),
    ]
